POST https://country-api-h3y9.onrender.com/paises
Content-Type: application/json
Accept-Language: pt-BR

  {
    "id": 55,
    "nome": "Brasil",
    "capital": "Brasília",
    "populacao": 215000000,
    "idioma": "Português",
    "area": 8515767.049
  }

###
GET https://country-api-h3y9.onrender.com/paises

###
PUT https://country-api-h3y9.onrender.com/paises/55
Content-Type: application/json

  {
    "id": 55,
    "nome": "Brasil",
    "capital": "Brasília",
    "populacao": 215000000,
    "idioma": "Português",
    "area": 8515767.049
  }

###
DELETE https://country-api-h3y9.onrender.com/paises
