POST https://country-api-mqyt.onrender.com/paises
Content-Type: application/json
Accept-Language: pt-BR

  {
    "id": 56,
    "nome": "Brasil",
    "capital": "Brasília",
    "populacao": 215000000,
    "idioma": "Português",
    "area": 8515767.049
  }

###
GET http://localhost:3333/paises?search=brasil

###
PUT https://country-api-mqyt.onrender.com/paises/56
Content-Type: application/json

  {
    "id": 57,
    "nome": "Brasil",
    "capital": "Brasília",
    "populacao": 215000000,
    "idioma": "Português",
    "area": 8515767.049
  }

###
DELETE https://country-api-mqyt.onrender.com/paises/56
